/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.LoadData;
import controller.UrunYukle;
import java.awt.BorderLayout;
import model.Kullanici;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import model.Urun;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
import org.hibernate.cfg.Configuration;
import org.hibernate.service.ServiceRegistry;

public final class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }
    private static Session sessionObj;
    private static SessionFactory sessionFactoryObj;
    private static int urunId;
    private long control;
    private UrunYukle urunYukle = new UrunYukle();
    private static List<Urun> sepettekiUrunler;

    private static SessionFactory buildSessionFactory() {
        // Creating Configuration Instance & Passing Hibernate Configuration File
        Configuration configObj = new Configuration();
        configObj.configure("hibernate.cfg.xml");

        ServiceRegistry serviceRegistryObj = new StandardServiceRegistryBuilder().applySettings(configObj.getProperties()).build();

        // Creating Hibernate SessionFactory Instance
        sessionFactoryObj = configObj.buildSessionFactory(serviceRegistryObj);
        return sessionFactoryObj;
    }

    public void panelDegistir(javax.swing.JPanel panel) {   //paneller arasında geçiş yapmak için kullanılan metod
        mainPanel.removeAll();  //paneldeki tüm componentleri kaldırıyoruz(yenilerini yükleyip güncellemek için)
        mainPanel.add(panel);   //geçilecek paneli mainPanel'e(JLayeredPane) ekliyoruz
        mainPanel.revalidate(); //yeni componentler eklediğimizden layoutmanagere layoutun yeniden hesaplanması gerektiğini bildiriyoruz
        mainPanel.repaint();    //layoutu etkileyecek şekilde değişen componentleri repaint ediyoruz
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JLayeredPane();
        girisPanel = new javax.swing.JPanel();
        girisPanelInternal = new javax.swing.JPanel();
        girisParolaText = new javax.swing.JPasswordField();
        kAdGirisL = new javax.swing.JLabel();
        parolaGirisL = new javax.swing.JLabel();
        GirisKAdiText = new javax.swing.JTextField();
        girisYapButton = new javax.swing.JButton();
        kayitOlButton = new javax.swing.JButton();
        girisBilgiL = new javax.swing.JLabel();
        uyeOlPanel = new javax.swing.JPanel();
        uyeOlPanelInternal = new javax.swing.JPanel();
        uyeOlparolaText = new javax.swing.JPasswordField();
        kAdUyeOlL = new javax.swing.JLabel();
        parolaUyeOlL = new javax.swing.JLabel();
        uyeOlKAdiText = new javax.swing.JTextField();
        uyeOlGirisButton = new javax.swing.JButton();
        uyeOlUyeButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        uyeOlPostaText = new javax.swing.JTextField();
        uyeOlTelText = new javax.swing.JTextField();
        uyeOlParolaTekrarText = new javax.swing.JPasswordField();
        parolaUyeOlTekrarL = new javax.swing.JLabel();
        uyeOlBilgiL = new javax.swing.JLabel();
        marketPanel = new javax.swing.JPanel();
        marketPanelInternal = new javax.swing.JPanel();
        urunPanelScrollP = new javax.swing.JScrollPane();
        urunP = new javax.swing.JPanel();
        sagPanel = new javax.swing.JPanel();
        cuzdanL = new javax.swing.JLabel();
        cuzdanBilgiL = new javax.swing.JLabel();
        tlL = new javax.swing.JLabel();
        sepetinizL = new javax.swing.JLabel();
        urunSepetScrollP = new javax.swing.JScrollPane();
        urunSepet = new javax.swing.JPanel();
        sepetBilgiL = new javax.swing.JLabel();
        satinAlButton = new javax.swing.JButton();
        sepetiBosaltButton = new javax.swing.JButton();
        cikisButton = new javax.swing.JButton();
        bakiyeYukleButton = new javax.swing.JButton();
        bakiyePanel = new javax.swing.JPanel();
        bakiyePanelInternal = new javax.swing.JPanel();
        kartNumaraL = new javax.swing.JLabel();
        sonKL = new javax.swing.JLabel();
        cvvL = new javax.swing.JLabel();
        yukleButton = new javax.swing.JButton();
        kartNumText = new javax.swing.JTextField();
        sKText = new javax.swing.JTextField();
        cvvText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bakiyeMiktarText = new javax.swing.JTextField();
        bakiyeCuzdanL = new javax.swing.JLabel();
        bakiyeCuzdanBilgiL = new javax.swing.JLabel();
        bakiyeTLL = new javax.swing.JLabel();
        bakiyeGeriButton = new javax.swing.JButton();
        bakiyeCikisButton = new javax.swing.JButton();
        bakiyeBilgiL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Market"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 960));

        mainPanel.setPreferredSize(new java.awt.Dimension(1280, 960));
        mainPanel.setLayout(new java.awt.CardLayout());

        girisPanel.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2, true));

        girisPanelInternal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        girisParolaText.setAlignmentX(CENTER_ALIGNMENT);
        girisParolaText.setAlignmentY(CENTER_ALIGNMENT);
        girisParolaText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                girisParolaTextFocusGained(evt);
            }
        });
        girisParolaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisParolaTextActionPerformed(evt);
            }
        });

        kAdGirisL.setText("Kullanıcı Adı");
        kAdGirisL.setAlignmentX(CENTER_ALIGNMENT);
        kAdGirisL.setAlignmentY(CENTER_ALIGNMENT);

        parolaGirisL.setText("Parola");
        parolaGirisL.setAlignmentX(CENTER_ALIGNMENT);
        parolaGirisL.setAlignmentY(CENTER_ALIGNMENT);

        GirisKAdiText.setAlignmentX(CENTER_ALIGNMENT);
        GirisKAdiText.setAlignmentY(CENTER_ALIGNMENT);
        GirisKAdiText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GirisKAdiTextActionPerformed(evt);
            }
        });

        girisYapButton.setText("Giriş Yap");
        girisYapButton.setAlignmentX(CENTER_ALIGNMENT);
        girisYapButton.setAlignmentY(CENTER_ALIGNMENT);
        girisYapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisYapButtonActionPerformed(evt);
            }
        });

        kayitOlButton.setText("Kayıt Ol");
        kayitOlButton.setAlignmentX(CENTER_ALIGNMENT);
        kayitOlButton.setAlignmentY(CENTER_ALIGNMENT);
        kayitOlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayitOlButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout girisPanelInternalLayout = new javax.swing.GroupLayout(girisPanelInternal);
        girisPanelInternal.setLayout(girisPanelInternalLayout);
        girisPanelInternalLayout.setHorizontalGroup(
            girisPanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, girisPanelInternalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(girisPanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GirisKAdiText, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(girisParolaText))
                .addGap(28, 28, 28))
            .addGroup(girisPanelInternalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(girisYapButton, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(kayitOlButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(girisPanelInternalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(girisBilgiL, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(girisPanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(girisPanelInternalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(girisPanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(parolaGirisL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kAdGirisL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(182, Short.MAX_VALUE)))
        );
        girisPanelInternalLayout.setVerticalGroup(
            girisPanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(girisPanelInternalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GirisKAdiText)
                .addGap(33, 33, 33)
                .addComponent(girisParolaText)
                .addGap(18, 18, 18)
                .addGroup(girisPanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(girisYapButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kayitOlButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(girisBilgiL, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(girisPanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(girisPanelInternalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(kAdGirisL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(30, 30, 30)
                    .addComponent(parolaGirisL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(123, 123, 123)))
        );

        javax.swing.GroupLayout girisPanelLayout = new javax.swing.GroupLayout(girisPanel);
        girisPanel.setLayout(girisPanelLayout);
        girisPanelLayout.setHorizontalGroup(
            girisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, girisPanelLayout.createSequentialGroup()
                .addContainerGap(514, Short.MAX_VALUE)
                .addComponent(girisPanelInternal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(498, Short.MAX_VALUE))
        );
        girisPanelLayout.setVerticalGroup(
            girisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, girisPanelLayout.createSequentialGroup()
                .addContainerGap(368, Short.MAX_VALUE)
                .addComponent(girisPanelInternal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(375, Short.MAX_VALUE))
        );

        mainPanel.add(girisPanel, "card2");

        uyeOlPanel.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2, true));

        uyeOlPanelInternal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        uyeOlparolaText.setAlignmentX(CENTER_ALIGNMENT);
        uyeOlparolaText.setAlignmentY(CENTER_ALIGNMENT);
        uyeOlparolaText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                uyeOlparolaTextFocusGained(evt);
            }
        });
        uyeOlparolaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyeOlparolaTextActionPerformed(evt);
            }
        });

        kAdUyeOlL.setText("Kullanıcı Adı");
        kAdUyeOlL.setAlignmentX(CENTER_ALIGNMENT);
        kAdUyeOlL.setAlignmentY(CENTER_ALIGNMENT);

        parolaUyeOlL.setText("Parola");
        parolaUyeOlL.setAlignmentX(CENTER_ALIGNMENT);
        parolaUyeOlL.setAlignmentY(CENTER_ALIGNMENT);

        uyeOlKAdiText.setAlignmentX(CENTER_ALIGNMENT);
        uyeOlKAdiText.setAlignmentY(CENTER_ALIGNMENT);
        uyeOlKAdiText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyeOlKAdiTextActionPerformed(evt);
            }
        });

        uyeOlGirisButton.setText("Giriş Yap");
        uyeOlGirisButton.setAlignmentX(CENTER_ALIGNMENT);
        uyeOlGirisButton.setAlignmentY(CENTER_ALIGNMENT);
        uyeOlGirisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyeOlGirisButtonActionPerformed(evt);
            }
        });

        uyeOlUyeButton.setText("Üye Ol");
        uyeOlUyeButton.setAlignmentX(CENTER_ALIGNMENT);
        uyeOlUyeButton.setAlignmentY(CENTER_ALIGNMENT);
        uyeOlUyeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyeOlUyeButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("E-Posta");
        jLabel2.setAlignmentX(CENTER_ALIGNMENT);
        jLabel2.setAlignmentY(CENTER_ALIGNMENT);

        jLabel3.setText("Telefon");
        jLabel3.setAlignmentX(CENTER_ALIGNMENT);
        jLabel3.setAlignmentY(CENTER_ALIGNMENT);

        uyeOlPostaText.setAlignmentX(CENTER_ALIGNMENT);
        uyeOlPostaText.setAlignmentY(CENTER_ALIGNMENT);
        uyeOlPostaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyeOlPostaTextActionPerformed(evt);
            }
        });

        uyeOlTelText.setAlignmentX(CENTER_ALIGNMENT);
        uyeOlTelText.setAlignmentY(CENTER_ALIGNMENT);

        uyeOlParolaTekrarText.setAlignmentX(CENTER_ALIGNMENT);
        uyeOlParolaTekrarText.setAlignmentY(CENTER_ALIGNMENT);
        uyeOlParolaTekrarText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                uyeOlParolaTekrarTextFocusGained(evt);
            }
        });
        uyeOlParolaTekrarText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyeOlParolaTekrarTextActionPerformed(evt);
            }
        });

        parolaUyeOlTekrarL.setText("Parola Tekrar");
        parolaUyeOlTekrarL.setAlignmentX(CENTER_ALIGNMENT);
        parolaUyeOlTekrarL.setAlignmentY(CENTER_ALIGNMENT);

        javax.swing.GroupLayout uyeOlPanelInternalLayout = new javax.swing.GroupLayout(uyeOlPanelInternal);
        uyeOlPanelInternal.setLayout(uyeOlPanelInternalLayout);
        uyeOlPanelInternalLayout.setHorizontalGroup(
            uyeOlPanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uyeOlPanelInternalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(uyeOlPanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uyeOlPanelInternalLayout.createSequentialGroup()
                        .addGroup(uyeOlPanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kAdUyeOlL)
                            .addComponent(parolaUyeOlL)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(parolaUyeOlTekrarL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(uyeOlPanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(uyeOlPanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(uyeOlKAdiText, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(uyeOlparolaText, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(uyeOlParolaTekrarText, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uyeOlPanelInternalLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(uyeOlPanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(uyeOlPostaText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uyeOlTelText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(uyeOlPanelInternalLayout.createSequentialGroup()
                        .addComponent(uyeOlGirisButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(uyeOlUyeButton))
                    .addGroup(uyeOlPanelInternalLayout.createSequentialGroup()
                        .addComponent(uyeOlBilgiL, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        uyeOlPanelInternalLayout.setVerticalGroup(
            uyeOlPanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uyeOlPanelInternalLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(uyeOlPanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uyeOlPanelInternalLayout.createSequentialGroup()
                        .addComponent(kAdUyeOlL)
                        .addGap(30, 30, 30)
                        .addComponent(parolaUyeOlL)
                        .addGap(18, 18, 18)
                        .addComponent(parolaUyeOlTekrarL)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(uyeOlPanelInternalLayout.createSequentialGroup()
                        .addComponent(uyeOlKAdiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uyeOlparolaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uyeOlParolaTekrarText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(uyeOlPostaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uyeOlTelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(uyeOlPanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uyeOlGirisButton)
                    .addComponent(uyeOlUyeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(uyeOlBilgiL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout uyeOlPanelLayout = new javax.swing.GroupLayout(uyeOlPanel);
        uyeOlPanel.setLayout(uyeOlPanelLayout);
        uyeOlPanelLayout.setHorizontalGroup(
            uyeOlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uyeOlPanelLayout.createSequentialGroup()
                .addGap(0, 523, Short.MAX_VALUE)
                .addComponent(uyeOlPanelInternal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 524, Short.MAX_VALUE))
        );
        uyeOlPanelLayout.setVerticalGroup(
            uyeOlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uyeOlPanelLayout.createSequentialGroup()
                .addContainerGap(312, Short.MAX_VALUE)
                .addComponent(uyeOlPanelInternal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(334, Short.MAX_VALUE))
        );

        mainPanel.add(uyeOlPanel, "card2");

        marketPanel.setPreferredSize(new java.awt.Dimension(1280, 960));
        marketPanel.setRequestFocusEnabled(false);

        marketPanelInternal.setPreferredSize(new java.awt.Dimension(1180, 860));

        urunPanelScrollP.setViewportBorder(BorderFactory.createLineBorder(Color.ORANGE, 1, true)
        );
        urunPanelScrollP.setAutoscrolls(true);

        urunP.setMinimumSize(new java.awt.Dimension(27, 27));
        urunP.setOpaque(false);
        urunP.setLayout(new java.awt.GridLayout(9, 9, 10, 10));
        urunPanelScrollP.setViewportView(urunP);

        sagPanel.setLayout(new BorderLayout(2,2));
        sagPanel.setBorder(BorderFactory.createLineBorder(Color.magenta, 3, true));

        cuzdanL.setText("Cüzdan:");

        cuzdanBilgiL.setText("-");

        tlL.setText("TL");

        sepetinizL.setText("Sepetiniz");
        sepetinizL.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1, true)
        );

        urunSepet.setLayout(new java.awt.GridLayout(9, 9, 10, 10));
        urunSepetScrollP.setViewportView(urunSepet);

        sepetBilgiL.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));

        satinAlButton.setText("Satın Al");
        satinAlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satinAlButtonActionPerformed(evt);
            }
        });

        sepetiBosaltButton.setText("Sepeti Boşalt");
        sepetiBosaltButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sepetiBosaltButtonActionPerformed(evt);
            }
        });

        cikisButton.setText("Çıkış yap");
        cikisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisButtonActionPerformed(evt);
            }
        });

        bakiyeYukleButton.setText("Yükle");
        bakiyeYukleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakiyeYukleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sagPanelLayout = new javax.swing.GroupLayout(sagPanel);
        sagPanel.setLayout(sagPanelLayout);
        sagPanelLayout.setHorizontalGroup(
            sagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sagPanelLayout.createSequentialGroup()
                .addComponent(cikisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(sagPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sepetBilgiL, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addComponent(urunSepetScrollP)
                    .addGroup(sagPanelLayout.createSequentialGroup()
                        .addGroup(sagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sepetinizL)
                            .addGroup(sagPanelLayout.createSequentialGroup()
                                .addComponent(cuzdanL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cuzdanBilgiL, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tlL)
                                .addGap(18, 18, 18)
                                .addComponent(bakiyeYukleButton))
                            .addGroup(sagPanelLayout.createSequentialGroup()
                                .addComponent(satinAlButton)
                                .addGap(18, 18, 18)
                                .addComponent(sepetiBosaltButton)))
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        sagPanelLayout.setVerticalGroup(
            sagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sagPanelLayout.createSequentialGroup()
                .addComponent(cikisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(sagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuzdanBilgiL)
                    .addComponent(cuzdanL)
                    .addComponent(tlL)
                    .addComponent(bakiyeYukleButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepetinizL)
                .addGap(18, 18, 18)
                .addComponent(urunSepetScrollP, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(satinAlButton, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sepetiBosaltButton, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sepetBilgiL, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout marketPanelInternalLayout = new javax.swing.GroupLayout(marketPanelInternal);
        marketPanelInternal.setLayout(marketPanelInternalLayout);
        marketPanelInternalLayout.setHorizontalGroup(
            marketPanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marketPanelInternalLayout.createSequentialGroup()
                .addComponent(urunPanelScrollP, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sagPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        marketPanelInternalLayout.setVerticalGroup(
            marketPanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(urunPanelScrollP)
            .addComponent(sagPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout marketPanelLayout = new javax.swing.GroupLayout(marketPanel);
        marketPanel.setLayout(marketPanelLayout);
        marketPanelLayout.setHorizontalGroup(
            marketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marketPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(marketPanelInternal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        marketPanelLayout.setVerticalGroup(
            marketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marketPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(marketPanelInternal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPanel.add(marketPanel, "card4");

        bakiyePanel.setPreferredSize(new java.awt.Dimension(1080, 768));

        bakiyePanelInternal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        kartNumaraL.setText("Kart Numarası:");

        sonKL.setText("SK Tarihi");

        cvvL.setText("CVV");

        yukleButton.setText("Bakiye yükle");
        yukleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yukleButtonActionPerformed(evt);
            }
        });

        kartNumText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kartNumTextActionPerformed(evt);
            }
        });

        jLabel1.setText("Miktar:");

        javax.swing.GroupLayout bakiyePanelInternalLayout = new javax.swing.GroupLayout(bakiyePanelInternal);
        bakiyePanelInternal.setLayout(bakiyePanelInternalLayout);
        bakiyePanelInternalLayout.setHorizontalGroup(
            bakiyePanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bakiyePanelInternalLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(bakiyeMiktarText, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(324, Short.MAX_VALUE))
            .addGroup(bakiyePanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bakiyePanelInternalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(bakiyePanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bakiyePanelInternalLayout.createSequentialGroup()
                            .addComponent(sonKL)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sKText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cvvL)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cvvText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(bakiyePanelInternalLayout.createSequentialGroup()
                            .addComponent(kartNumaraL)
                            .addGap(18, 18, 18)
                            .addComponent(kartNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(bakiyePanelInternalLayout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addComponent(yukleButton)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        bakiyePanelInternalLayout.setVerticalGroup(
            bakiyePanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bakiyePanelInternalLayout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(bakiyePanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bakiyeMiktarText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
            .addGroup(bakiyePanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bakiyePanelInternalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(bakiyePanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(kartNumaraL)
                        .addComponent(kartNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(21, 21, 21)
                    .addGroup(bakiyePanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sonKL)
                        .addComponent(cvvL)
                        .addComponent(sKText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cvvText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(48, 48, 48)
                    .addComponent(yukleButton)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        bakiyeCuzdanL.setText("Cüzdan:");

        bakiyeCuzdanBilgiL.setText("-");

        bakiyeTLL.setText("TL");

        bakiyeGeriButton.setText("Geri");
        bakiyeGeriButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakiyeGeriButtonActionPerformed(evt);
            }
        });

        bakiyeCikisButton.setText("Çıkış");
        bakiyeCikisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakiyeCikisButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bakiyePanelLayout = new javax.swing.GroupLayout(bakiyePanel);
        bakiyePanel.setLayout(bakiyePanelLayout);
        bakiyePanelLayout.setHorizontalGroup(
            bakiyePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bakiyePanelLayout.createSequentialGroup()
                .addGap(416, 416, 416)
                .addGroup(bakiyePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bakiyeBilgiL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bakiyePanelInternal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bakiyePanelLayout.createSequentialGroup()
                        .addComponent(bakiyeCuzdanL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bakiyeCuzdanBilgiL, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bakiyeTLL))
                    .addGroup(bakiyePanelLayout.createSequentialGroup()
                        .addComponent(bakiyeGeriButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bakiyeCikisButton)))
                .addGap(375, 375, 375))
        );
        bakiyePanelLayout.setVerticalGroup(
            bakiyePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bakiyePanelLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addGroup(bakiyePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bakiyeCuzdanL)
                    .addComponent(bakiyeCuzdanBilgiL)
                    .addComponent(bakiyeTLL)
                    .addComponent(bakiyeGeriButton)
                    .addGroup(bakiyePanelLayout.createSequentialGroup()
                        .addComponent(bakiyeCikisButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bakiyePanelInternal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(bakiyeBilgiL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(501, Short.MAX_VALUE))
        );

        mainPanel.add(bakiyePanel, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GirisKAdiTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GirisKAdiTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GirisKAdiTextActionPerformed

    private void kayitOlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayitOlButtonActionPerformed
        panelDegistir(uyeOlPanel);
    }//GEN-LAST:event_kayitOlButtonActionPerformed

    private void girisYapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisYapButtonActionPerformed
        //giriş yap butonuna tıklandığında tetiklenen metod
        String parola = new String(girisParolaText.getPassword());  //parolamızı alıyoruz
        if (GirisKAdiText.getText().isEmpty() || parola.isEmpty()) { //boş alan varsa uyarıyoruz
            girisBilgiL.setText("Boş alan bırakmayınız");
        } else {
            try {
                sessionObj = buildSessionFactory().openSession();   //yeni bir session aç
                sessionObj.beginTransaction();  //işlemi başlat
                Query query = sessionObj.createQuery("from Kullanici K where K.kullaniciAdi=:gelenKAd and K.parola=:parola");  //girilen kullanıcı adı ve parola ile veri tabanında kayıt olup olmadığını sorguluyoruz
                query.setParameter("gelenKAd", GirisKAdiText.getText()); //hql sorgusunda parametre olarak kullandığımız gelenKAd'a kullanıcının girdiği kullanıcı adını atıyoruz
                query.setParameter("parola", parola);   //hql sorgusunda parametre olarak kullandığımız parola'ya kullanıcının girdiği parolayı atıyoruz
                Kullanici kullaniciKontrol = (Kullanici) query.uniqueResult();   //tek bir veri alacağımız için uniqueResult() metodu ile sorguyu gerçekleştiriyoruz
                if (kullaniciKontrol == null) { //eğer veri tabanında böyle bir kayıt yoksa uyarıyoruz
                    girisBilgiL.setText("Kullanıcı adı ya da parola yanlış");
                } else {
                    LoginData.setKullaniciBilgi(new Kullanici(kullaniciKontrol.getId(), kullaniciKontrol.getAd(), kullaniciKontrol.getParola(), kullaniciKontrol.getCuzdan())); //giriş yapan kullanıcıya ait bilgileri static bir değişkende tutuyoruz
                    urunYukle.doldur(urunP, urunSepet, cuzdanBilgiL, buildSessionFactory());    //urunPanel sayfasına yönlendirileceği için bu paneli hazırlıyoruz
                    girisBilgiL.setText("");
                    panelDegistir(marketPanel);
                }
                sessionObj.getTransaction().commit();
            } catch (Exception sqlException) {
                if (null != sessionObj.getTransaction()) {
                    sessionObj.getTransaction().rollback();
                }
                sqlException.printStackTrace();
            }
        }
    }//GEN-LAST:event_girisYapButtonActionPerformed

    private void uyeOlKAdiTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyeOlKAdiTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uyeOlKAdiTextActionPerformed

    private void uyeOlGirisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyeOlGirisButtonActionPerformed
        //giriş yapmak için kullanılan panelden üye olmak için kullanılan panele geçişte üye olunan panelin bilgilerini sıfırlıyoruz
        uyeOlKAdiText.setText("");
        uyeOlparolaText.setText("");
        uyeOlParolaTekrarText.setText("");
        uyeOlPostaText.setText("");
        uyeOlTelText.setText("");
        uyeOlBilgiL.setText("");
        panelDegistir(girisPanel);
    }//GEN-LAST:event_uyeOlGirisButtonActionPerformed

    private void uyeOlUyeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyeOlUyeButtonActionPerformed
        String parola = new String(uyeOlparolaText.getPassword());
        String parolaTekrar = new String(uyeOlParolaTekrarText.getPassword());
        if (uyeOlKAdiText.getText().isEmpty() || parola.isEmpty() || parolaTekrar.isEmpty() || uyeOlPostaText.getText().isEmpty() || uyeOlTelText.getText().isEmpty()) {
            uyeOlBilgiL.setText("Boş alan bırakmayınız");
        } else if (!parola.equals(parolaTekrar)) {
            uyeOlBilgiL.setText("Parolalar eşleşmiyor");
        } else {
            try {
                sessionObj = buildSessionFactory().openSession();
                sessionObj.beginTransaction();
                Query query = sessionObj.createQuery("select count(1) from Kullanici K where K.kullaniciAdi=:gelenKAd");  //kullanıcının girdiği kullanıcı adı ile alınmış kayıt olup olmadığını anlamak için sorgu oluşturuyoruz
                query.setParameter("gelenKAd", uyeOlKAdiText.getText()); //hql sorgusunda parametre olarak kullandığımız gelenKAd'a kullanıcının girdiği kullanıcı adını atıyoruz
                control = (long) query.uniqueResult();   //tek bir veri alacağımız için uniqueResult() metodu ile sorguyu gerçekleştiriyoruz
                if (control != 0) { //eğer kullanıcı adı kullanılmış ise sorgumuz 0'dan farlı(1) döneceğinden bu şekilde kontrol ediyoruz
                    uyeOlBilgiL.setText("Kullanıcı adı geçersiz");
                } else {
                    sessionObj.save(new Kullanici(uyeOlKAdiText.getText(), parola, "user", uyeOlPostaText.getText()));
                    uyeOlBilgiL.setText("Kayıt başarılı");
                }
                sessionObj.getTransaction().commit();
            } catch (Exception sqlException) {
                if (null != sessionObj.getTransaction()) {
                    sessionObj.getTransaction().rollback();
                }
                sqlException.printStackTrace();
            } finally {
                if (sessionObj != null) {
                    sessionObj.close();
                }
            }
        }
    }//GEN-LAST:event_uyeOlUyeButtonActionPerformed

    private void girisParolaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisParolaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_girisParolaTextActionPerformed

    private void uyeOlparolaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyeOlparolaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uyeOlparolaTextActionPerformed

    private void uyeOlPostaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyeOlPostaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uyeOlPostaTextActionPerformed

    private void uyeOlparolaTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uyeOlparolaTextFocusGained

    }//GEN-LAST:event_uyeOlparolaTextFocusGained

    private void girisParolaTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_girisParolaTextFocusGained

    }//GEN-LAST:event_girisParolaTextFocusGained

    private void uyeOlParolaTekrarTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uyeOlParolaTekrarTextFocusGained

    }//GEN-LAST:event_uyeOlParolaTekrarTextFocusGained

    private void uyeOlParolaTekrarTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyeOlParolaTekrarTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uyeOlParolaTekrarTextActionPerformed

    private void satinAlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satinAlButtonActionPerformed
        float sepetUcret = 0, yeniBakiye = 0;
        Kullanici kullanici = LoginData.getKullaniciBilgi();
        for (Urun urun : sepettekiUrunler) {    //sepetteki ürünlerin toplam fiyatını hesaplıyoruz
            sepetUcret += urun.getUcret();
        }
        yeniBakiye = kullanici.getCuzdan() - sepetUcret;    //alışverişten sonra yüklenecek yeni bakiyeyi belirliyoruz
        if (sepettekiUrunler.isEmpty()) {
            sepetBilgiL.setText("Sepette ürün yok");
        } else if (kullanici.getCuzdan() < sepetUcret) {    //kullanıcının cüzdanında yeterli bakiye yoksa
            sepetBilgiL.setText("Yetersiz bakiye");
        } else {    //kullanıcının cüzdanında yeterli bakiye varsa
            try {
                sessionObj = sessionFactoryObj.openSession();
                sessionObj.beginTransaction();
                String hql = "update Kullanici set kullanici_cuzdan=:yeniBakiye where id=:kullaniciId"; //yeni bakiyeyi veri tabanında güncelliyoruz
                Query query = sessionObj.createQuery(hql);
                query.setParameter("kullaniciId", kullanici.getId());
                query.setParameter("yeniBakiye", yeniBakiye);
                int result = query.executeUpdate();
                cuzdanBilgiL.setText(String.valueOf(yeniBakiye));
                kullanici.setCuzdan(yeniBakiye);
                LoginData.setKullaniciBilgi(kullanici);
                sepettekiUrunler.clear();
                urunSepet.removeAll();
                urunSepet.revalidate();
                urunSepet.repaint();
                sepetBilgiL.setText("Satın alma başarılı");
                sessionObj.getTransaction().commit();
            } catch (Exception sqlException) {
                if (null != sessionObj.getTransaction()) {
                    sessionObj.getTransaction().rollback();
                }
                sqlException.printStackTrace();
            } finally {
                if (sessionObj != null) {
                    sessionObj.close();
                }
            }
        }
    }//GEN-LAST:event_satinAlButtonActionPerformed

    private void sepetiBosaltButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sepetiBosaltButtonActionPerformed
        //kullanıcı sepeti boşaltmak istediğinde
        sepettekiUrunler.clear();   //sepettekiUrunlar listemizi de temizliyoruz(listeden panele tekrar eklediğimizde eski ürünlerin eklenmemesi için)
        urunSepet.removeAll();
        urunSepet.revalidate();
        urunSepet.repaint();
        sepetBilgiL.setText("Sepet boşaltıldı");
    }//GEN-LAST:event_sepetiBosaltButtonActionPerformed

    private void cikisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisButtonActionPerformed
        //çıkış yaparken static değişkenimizdeki kullanıcı bilgilerini yeni bir obje kullanarak sıfırlıyoruz
        int input = JOptionPane.showConfirmDialog(null, "Çıkmak istediğinize emin misiniz?", "Çıkış", JOptionPane.YES_NO_OPTION);
        if (input == 0) { //yes
            LoginData.setKullaniciBilgi(new Kullanici());
            panelDegistir(girisPanel);
        }
    }//GEN-LAST:event_cikisButtonActionPerformed

    private void kartNumTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kartNumTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kartNumTextActionPerformed

    private void bakiyeYukleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakiyeYukleButtonActionPerformed
        bakiyeCuzdanBilgiL.setText(String.valueOf(LoginData.getKullaniciBilgi().getCuzdan()));
        panelDegistir(bakiyePanel);
    }//GEN-LAST:event_bakiyeYukleButtonActionPerformed

    private void yukleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yukleButtonActionPerformed
        //bakiye yüklemek için kullanılan buton için kullanılan ActionPerformed
        if (kartNumText.getText().isEmpty() || sKText.getText().isEmpty() || cvvText.getText().isEmpty() || bakiyeMiktarText.getText().isEmpty()) {
            bakiyeBilgiL.setText("Boş bilgi bırakmayınız");
        } else {
            Kullanici kullanici = LoginData.getKullaniciBilgi();
            float yeniBakiye = kullanici.getCuzdan() + Float.parseFloat(bakiyeMiktarText.getText());
            try {
                sessionObj = sessionFactoryObj.openSession();
                sessionObj.beginTransaction();
                String hql = "update Kullanici set kullanici_cuzdan=:yeniBakiye where id=:kullaniciId"; //kullanıcının cüzdanını güncelleyen hql sorgusu
                Query query = sessionObj.createQuery(hql);
                query.setParameter("kullaniciId", kullanici.getId());
                query.setParameter("yeniBakiye", yeniBakiye);
                int result = query.executeUpdate();
                kullanici.setCuzdan(yeniBakiye);
                LoginData.setKullaniciBilgi(kullanici);
                bakiyeCuzdanBilgiL.setText(String.valueOf(yeniBakiye));
                bakiyeBilgiL.setText("Yükleme işlemi başarılı");
                bakiyePanel.revalidate();
                bakiyePanel.repaint();
                sessionObj.getTransaction().commit();
            } catch (Exception sqlException) {
                if (null != sessionObj.getTransaction()) {
                    sessionObj.getTransaction().rollback();
                }
                sqlException.printStackTrace();
            } finally {
                if (sessionObj != null) {
                    sessionObj.close();
                }
            }
        }
    }//GEN-LAST:event_yukleButtonActionPerformed

    private void bakiyeGeriButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakiyeGeriButtonActionPerformed
        cuzdanBilgiL.setText(String.valueOf(LoginData.getKullaniciBilgi().getCuzdan()));
        panelDegistir(marketPanel);
    }//GEN-LAST:event_bakiyeGeriButtonActionPerformed

    private void bakiyeCikisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakiyeCikisButtonActionPerformed
        cikisButtonActionPerformed(evt);
    }//GEN-LAST:event_bakiyeCikisButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        sessionObj = buildSessionFactory().openSession();
        LoadData ld = new LoadData(sessionObj);  //Program başladığında test amaçlı veritabanına veri yüklemek için oluşturduğumuz LoadData sınıfımıza, buildSessionFactory() metodunu kullanarak session objesinin referansını gönderiyoruz
        ld.loadAllData();  //verileri yüklüyoruz
        sepettekiUrunler = new ArrayList<>();

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);

            }
        });
    }

    public static List<Urun> getSepettekiUrunler() {
        return sepettekiUrunler;
    }

    public static void setSepettekiUrunler(List<Urun> sepettekiUrunler) {
        Main.sepettekiUrunler = sepettekiUrunler;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField GirisKAdiText;
    private javax.swing.JLabel bakiyeBilgiL;
    private javax.swing.JButton bakiyeCikisButton;
    private javax.swing.JLabel bakiyeCuzdanBilgiL;
    private javax.swing.JLabel bakiyeCuzdanL;
    private javax.swing.JButton bakiyeGeriButton;
    private javax.swing.JTextField bakiyeMiktarText;
    private javax.swing.JPanel bakiyePanel;
    private javax.swing.JPanel bakiyePanelInternal;
    private javax.swing.JLabel bakiyeTLL;
    private javax.swing.JButton bakiyeYukleButton;
    private javax.swing.JButton cikisButton;
    private javax.swing.JLabel cuzdanBilgiL;
    private javax.swing.JLabel cuzdanL;
    private javax.swing.JLabel cvvL;
    private javax.swing.JTextField cvvText;
    private javax.swing.JLabel girisBilgiL;
    private javax.swing.JPanel girisPanel;
    private javax.swing.JPanel girisPanelInternal;
    private javax.swing.JPasswordField girisParolaText;
    private javax.swing.JButton girisYapButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel kAdGirisL;
    private javax.swing.JLabel kAdUyeOlL;
    private javax.swing.JTextField kartNumText;
    private javax.swing.JLabel kartNumaraL;
    private javax.swing.JButton kayitOlButton;
    private javax.swing.JLayeredPane mainPanel;
    private javax.swing.JPanel marketPanel;
    private javax.swing.JPanel marketPanelInternal;
    private javax.swing.JLabel parolaGirisL;
    private javax.swing.JLabel parolaUyeOlL;
    private javax.swing.JLabel parolaUyeOlTekrarL;
    private javax.swing.JTextField sKText;
    private javax.swing.JPanel sagPanel;
    private javax.swing.JButton satinAlButton;
    private javax.swing.JLabel sepetBilgiL;
    private javax.swing.JButton sepetiBosaltButton;
    private javax.swing.JLabel sepetinizL;
    private javax.swing.JLabel sonKL;
    private javax.swing.JLabel tlL;
    private javax.swing.JPanel urunP;
    private javax.swing.JScrollPane urunPanelScrollP;
    private javax.swing.JPanel urunSepet;
    private javax.swing.JScrollPane urunSepetScrollP;
    private javax.swing.JLabel uyeOlBilgiL;
    private javax.swing.JButton uyeOlGirisButton;
    private javax.swing.JTextField uyeOlKAdiText;
    private javax.swing.JPanel uyeOlPanel;
    private javax.swing.JPanel uyeOlPanelInternal;
    private javax.swing.JPasswordField uyeOlParolaTekrarText;
    private javax.swing.JTextField uyeOlPostaText;
    private javax.swing.JTextField uyeOlTelText;
    private javax.swing.JButton uyeOlUyeButton;
    private javax.swing.JPasswordField uyeOlparolaText;
    private javax.swing.JButton yukleButton;
    // End of variables declaration//GEN-END:variables

}
